/**
 * GENERATED by scripts/bake-ink-name.mjs — do not edit by hand.
 * Rerun it whenever `profile.nameScript` changes.
 *
 * The Mongol-script name as a brush stroke, already turned for vertical-lr.
 * `/intro/ink-name.png`: R signed distance (±spread px, 128 = edge, ink
 * > 128), G when the brush reaches the pixel (0…255 of the writing).
 * `/intro/ink-name-mask.png`: the finished ink as alpha, for static signs.
 */
export const INK_NAME = {
  src: "/intro/ink-name.png",
  mask: "/intro/ink-name-mask.png",
  width: 335,
  height: 1456,
  /** SDF range each side of the edge, texture px. */
  spread: 20,
  /** Empty margin round the ink, texture px. */
  pad: 30,
  /** The stem's centre, 0…1 across the texture. */
  stemX: 0.5478,
} as const;
