/**
 * Interface strings — everything a component used to hard-code.
 *
 * Content (who he is, what he built) lives in `content.ts`; this is the frame
 * around it: labels, buttons, form messages, aria text. Kept separate because it
 * changes for different reasons — copy is edited when his story changes, this
 * when the interface does.
 *
 * `UiStrings` is inferred from the English table, so the Mongolian table is
 * checked key-for-key against it: a string added here and not translated is a
 * type error, not a silent English fallback.
 */

const en = {
  lang: {
    /** The toggle's own labels, always in their own script. */
    en: "EN",
    mn: "МН",
    switchTo: "Switch language",
    current: "English",
  },
  nav: {
    openMenu: "Open menu",
    closeMenu: "Close menu",
    siteMenu: "Site menu",
    backToTop: "back to top",
    home: "home",
    resume: "Resume",
    resumeAria: "Download resume (PDF)",
    online: "Online",
  },
  hero: {
    aria: "Introduction",
    currently: "Currently",
    scroll: "Scroll",
  },
  about: {
    aria: "Profile",
  },
  connect: {
    aria: "Find me elsewhere",
    eyebrow: "Find me elsewhere",
    title: "Signal",
    lead: "The code, the career history, and the résumé in English and Mongolian.",
    openPdf: "Open PDF",
    openProfile: "Open profile",
  },
  work: {
    aria: "Selected work",
    eyebrow: "Selected work",
    title: "Work",
    open: "Open case file",
    visit: "Visit site",
    prev: "Previous case file",
    next: "Next case file",
    rail: "Case files",
    hint: "Scroll, or use ← →",
    count: (i: number, n: number) => `${String(i).padStart(2, "0")} / ${String(n).padStart(2, "0")}`,
    noSite: "No public build",
    preview: (title: string) => `${title} — open case file`,
  },
  craft: {
    aria: "Capabilities",
    eyebrow: "What I do",
    title: "Craft",
    lead: "What I reach for, and where each one has been put to work.",
    proven: "Proven in",
  },
  path: {
    aria: "Experience and numbers",
    eyebrow: "Where I've been",
    title: "Path",
    numbers: "By the numbers",
    record: "Track record",
    work: "Work",
    education: "Education",
  },
  caseFile: {
    label: "Case file",
    close: "Close case file",
    overview: "Overview",
    outcomes: "Key outcomes",
    stack: "Stack",
    metrics: "Metrics",
    links: "Links",
    gallery: "Gallery",
    role: "Role",
    year: "Year",
    category: "Category",
    status: "Status",
    prev: "Previous",
    next: "Next",
    esc: "Esc to close",
  },
  contact: {
    aria: "Contact",
    title: "Let's build",
    email: "Email",
    availability: "Availability",
    based: "Based",
  },
  form: {
    name: "Name",
    email: "Email",
    message: "Message",
    namePlaceholder: "Your name",
    emailPlaceholder: "you@company.com",
    messagePlaceholder: "The role, the team, or anything you'd like to ask…",
    nameRequired: "Please add your name.",
    emailRequired: "Please add your email.",
    emailInvalid: "That email doesn't look right.",
    messageShort: "A little more, please (10+ characters).",
    send: "Send message",
    sending: "Sending",
    sent: "Message sent",
    retry: "Try again",
    another: "Send another",
    noClient: "No mail client answered. Write to",
    copied: "Address copied",
    copy: "Copy address",
    liveSent: "Your mail client has been opened.",
    liveNoClient: (email: string) => `No mail client answered. Write to ${email} instead.`,
    liveErrors: (n: number) => `${n} ${n === 1 ? "field needs" : "fields need"} attention.`,
    subject: (name: string) => `Hello from ${name}`,
  },
  footer: {
    aria: "Footer",
    index: "Index",
    elsewhere: "Elsewhere",
    top: "Top",
    /** Trademark credit for the marks on the Signal panels (see BrandMarks). */
    credit:
      "GitHub and the Invertocat logo are trademarks of GitHub, Inc. LinkedIn and the IN logo are registered trademarks of LinkedIn Corporation.",
  },
  palette: {
    aria: "Command palette",
    placeholder: "Jump to a section, a case file, or an action…",
    search: "Search commands",
    results: "Commands",
    sections: "Sections",
    caseFiles: "Case files",
    actions: "Actions",
    copyEmail: "Copy email address",
    copiedEmail: "Copied",
    lowPower: "Low-power mode",
    language: "Монгол хэлээр үзэх",
    on: "ON",
    off: "OFF",
    none: (q: string) => `Nothing matches “${q}”.`,
    keys: "↑↓ move · ↵ select · esc close",
    count: (n: number) => `${n} results`,
  },
  common: {
    newTab: "(opens in a new tab)",
  },
  notFound: {
    eyebrow: "Page not found",
    body: "This page doesn't exist — or it did, and doesn't any more.",
    back: "Back to the index",
  },
};

export type UiStrings = typeof en;

/**
 * Монгол. Draft for Amartuvshin to proofread — see the note in content.mn.ts.
 * Nav-scale labels are kept short on purpose: Mongolian runs longer than
 * English, and the navbar and the rail have fixed room.
 */
const mn: UiStrings = {
  lang: {
    en: "EN",
    mn: "МН",
    switchTo: "Хэл сонгох",
    current: "Монгол",
  },
  nav: {
    openMenu: "Цэс нээх",
    closeMenu: "Цэс хаах",
    siteMenu: "Сайтын цэс",
    backToTop: "дээш буцах",
    home: "нүүр",
    resume: "Резюме",
    resumeAria: "Резюме татах (PDF)",
    online: "Онлайн",
  },
  hero: {
    aria: "Танилцуулга",
    currently: "Одоо",
    scroll: "Гүйлгэх",
  },
  about: {
    aria: "Танилцуулга",
  },
  connect: {
    aria: "Бусад сувгууд",
    eyebrow: "Бусад сувгууд",
    title: "Холбоо",
    lead: "Код, ажлын туршлага, англи болон монгол хэл дээрх резюме.",
    openPdf: "PDF нээх",
    openProfile: "Профайл нээх",
  },
  work: {
    aria: "Сонгосон төслүүд",
    eyebrow: "Сонгосон төслүүд",
    title: "Төслүүд",
    open: "Дэлгэрэнгүй",
    visit: "Сайт үзэх",
    prev: "Өмнөх төсөл",
    next: "Дараах төсөл",
    rail: "Төслүүд",
    hint: "Гүйлгэх, эсвэл ← →",
    count: (i: number, n: number) => `${String(i).padStart(2, "0")} / ${String(n).padStart(2, "0")}`,
    noSite: "Нээлттэй хувилбаргүй",
    preview: (title: string) => `${title} — дэлгэрэнгүй нээх`,
  },
  craft: {
    aria: "Ур чадвар",
    eyebrow: "Юу хийдэг вэ",
    title: "Ур чадвар",
    lead: "Миний ашигладаг хэрэгслүүд, тус бүрийг хаана хэрэгжүүлснийг харуулав.",
    proven: "Хэрэгжүүлсэн",
  },
  path: {
    aria: "Туршлага ба тоонууд",
    eyebrow: "Туулсан зам",
    title: "Замнал",
    numbers: "Тоогоор",
    record: "Туршлага",
    work: "Ажил",
    education: "Боловсрол",
  },
  caseFile: {
    label: "Төслийн дэлгэрэнгүй",
    close: "Хаах",
    overview: "Тойм",
    outcomes: "Гол үр дүн",
    stack: "Технологи",
    metrics: "Үзүүлэлт",
    links: "Холбоос",
    gallery: "Зургууд",
    role: "Үүрэг",
    year: "Он",
    category: "Төрөл",
    status: "Төлөв",
    prev: "Өмнөх",
    next: "Дараах",
    esc: "Esc — хаах",
  },
  contact: {
    aria: "Холбогдох",
    title: "Хамтран ажиллая",
    email: "И-мэйл",
    availability: "Боломж",
    based: "Байршил",
  },
  form: {
    name: "Нэр",
    email: "И-мэйл",
    message: "Зурвас",
    namePlaceholder: "Таны нэр",
    emailPlaceholder: "you@company.com",
    messagePlaceholder: "Ажлын байр, баг, эсвэл асуух зүйлээ бичнэ үү…",
    nameRequired: "Нэрээ оруулна уу.",
    emailRequired: "И-мэйлээ оруулна уу.",
    emailInvalid: "И-мэйлийн хаяг буруу байна.",
    messageShort: "Арай дэлгэрэнгүй бичнэ үү (10+ тэмдэгт).",
    send: "Илгээх",
    sending: "Илгээж байна",
    sent: "Илгээгдлээ",
    retry: "Дахин оролдох",
    another: "Дахин илгээх",
    noClient: "И-мэйл програм нээгдсэнгүй. Энэ хаяг руу бичнэ үү:",
    copied: "Хаяг хуулагдлаа",
    copy: "Хаяг хуулах",
    liveSent: "Таны и-мэйл програм нээгдлээ.",
    liveNoClient: (email: string) => `И-мэйл програм нээгдсэнгүй. ${email} хаяг руу бичнэ үү.`,
    liveErrors: (n: number) => `${n} талбарыг засна уу.`,
    subject: (name: string) => `${name}-аас мэндчилгээ`,
  },
  footer: {
    aria: "Хөл хэсэг",
    index: "Агуулга",
    elsewhere: "Бусад",
    top: "Дээш",
    credit:
      "GitHub болон Invertocat лого нь GitHub, Inc.-ийн барааны тэмдэг. LinkedIn болон IN лого нь LinkedIn Corporation-ийн бүртгэлтэй барааны тэмдэг.",
  },
  palette: {
    aria: "Командын цонх",
    placeholder: "Хэсэг, төсөл эсвэл үйлдэл хайх…",
    search: "Команд хайх",
    results: "Командууд",
    sections: "Хэсгүүд",
    caseFiles: "Төслүүд",
    actions: "Үйлдлүүд",
    copyEmail: "И-мэйл хаяг хуулах",
    copiedEmail: "Хуулагдлаа",
    lowPower: "Хэмнэлттэй горим",
    language: "View in English",
    on: "ИДЭВХТЭЙ",
    off: "ИДЭВХГҮЙ",
    none: (q: string) => `“${q}”-д тохирох зүйл алга.`,
    keys: "↑↓ шилжих · ↵ сонгох · esc хаах",
    count: (n: number) => `${n} илэрц`,
  },
  common: {
    newTab: "(шинэ цонхонд нээгдэнэ)",
  },
  notFound: {
    eyebrow: "Хуудас олдсонгүй",
    body: "Энэ хуудас байхгүй — эсвэл байсан ч одоо алга.",
    back: "Нүүр хуудас руу буцах",
  },
};

export const ui: { en: UiStrings; mn?: UiStrings } = { en, mn };
