/**
 * Interface strings — everything a component used to hard-code.
 *
 * Content (who he is, what he built) lives in `content.ts`; this is the frame
 * around it: labels, buttons, form messages, aria text. Kept separate because it
 * changes for different reasons — copy is edited when his story changes, this
 * when the interface does.
 *
 * `UiStrings` is inferred from the English table, so the Mongolian table is
 * checked key-for-key against it: a string added here and not translated is a
 * type error, not a silent English fallback.
 */

/** The drawings a Capstone step can carry (components/anatomy/BeatDetail). */
export type BeatShow = "input" | "access" | "forest" | "override" | "neighbours" | "timing" | "measured" | "usability" | "fixes";

/** One step of the Capstone chapter. `station` names it on the rail; `plain`
 *  says it without the jargon; `show` lists its drawings, in order. */
type AnatomyBeat = { station: string; title: string; body: string; plain?: string; show: BeatShow[] };

const en = {
  lang: {
    /** The toggle's own labels, always in their own script. */
    en: "EN",
    mn: "МН",
    switchTo: "Switch language",
    current: "English",
  },
  preloader: {
    loading: "LOADING",
    writing: "WRITING",
    ready: "READY",
    /** The slate in the intro's top bar. */
    reel: "REEL 01 · ULAANBAATAR",
    skipKey: "Press any key to skip",
    skipTap: "Tap to skip",
  },
  nav: {
    openMenu: "Open menu",
    closeMenu: "Close menu",
    siteMenu: "Site menu",
    backToTop: "back to top",
    home: "home",
    /** The phone's menu button, visible text. */
    index: "Index",
  },
  hero: {
    aria: "Introduction",
    currently: "Currently",
    scroll: "Scroll",
  },
  about: {
    aria: "Profile",
    /** The dossier plate's extra fields. Both facts are already in the About
     *  copy ("fluent in Mongolian and English") and the hero status. */
    languages: "Languages",
    languagesValue: "Mongolian · English",
    status: "Status",
    file: "Personnel file",
  },
  connect: {
    aria: "Find me elsewhere",
    eyebrow: "Find me elsewhere",
    title: "Links",
    lead: "The code, the career history, and the live product.",
    openProfile: "Open profile",
    openSite: "Open live site",
    repos: (n: number) => `${n} public repos`,
    lastPush: "Last push",
    /** The live product's lamp in its panel readout. */
    live: "Live",
    recent: "Recently pushed",
    /** The copy-link button on each panel. */
    copy: (label: string) => `Copy ${label} link`,
    copied: "Copied",
    copyShort: "Copy link",
    langMix: "Language mix",
    repoLog: "Repo log",
    started: (name: string, when: string) => `${name}, started ${when}`,
    status: "Status",
  },
  work: {
    aria: "Selected work",
    eyebrow: "Selected work",
    title: "Work",
    open: "Open case file",
    /** The cursor's label over a case file you can open. */
    view: "VIEW",
    visit: "Visit site",
    prev: "Previous case file",
    next: "Next case file",
    rail: "Case files",
    hint: "Scroll, or use ← →",
    count: (i: number, n: number) => `${String(i).padStart(2, "0")} / ${String(n).padStart(2, "0")}`,
    noSite: "No public build",
    preview: (title: string) => `${title} — open case file`,
  },
  craft: {
    aria: "Skills",
    eyebrow: "What I do",
    title: "Skills",
    lead: "What I reach for, and where each one has been put to work.",
    proven: "Proven in",
    stack: "Tools",
    /** The master logo dock under the header. */
    dock: "Tech stack",
    studied: "Studied at Gannon",
    degree: (credits: number, deans: number) =>
      `B.S. Software Engineering · ${credits} credits · Dean's List ×${deans}`,
    hint: "Keep scrolling",
    tools: {
      usability: "Usability testing",
      accessibility: "Accessibility",
      testcases: "Test cases",
      defects: "Defect tracking",
      sdlc: "SDLC",
    },
  },
  anatomy: {
    aria: "How Spotfixes works: from a bug report to a severity rating",
    eyebrow: "Capstone · team of 3",
    title: "How Spotfixes works",
    credit: "My part: UI/UX lead and testing",
    source: "Based on our final capstone report, spring 2026",
    hint: "Scroll or use ← → keys",
    step: (i: number, n: number) => `${String(i).padStart(2, "0")} / ${String(n).padStart(2, "0")}`,
    goTo: (title: string) => `Show: ${title}`,
    illustrative: "Example",
    exampleLabel: "Example report",
    beats: [
      {
        station: "Report",
        title: "A bug report comes in",
        body: "A developer types a short description of what went wrong, and Spotfixes sends it to the server to be checked.",
        show: ["input"],
      },
      {
        station: "Security",
        title: "It checks who's asking",
        body: "Every request carries a signed login token, and the server turns away fake or expired ones. Each company can only ever see its own bugs.",
        plain: "Think of an apartment building: every company has its own front door, and nobody can walk into someone else's flat.",
        show: ["access"],
      },
      {
        station: "Severity",
        title: "It rates how serious the bug is",
        body: "A machine-learning model scores each word, then hundreds of small decision trees vote on a rating from S1 (most serious) to S4. Words like “crash”, “security” or “leak” always make it S1.",
        plain: "The model can't read English, so each word gets a score for how much it matters: “crash” scores high, “the” scores zero.",
        show: ["forest", "override"],
      },
      {
        station: "Duplicates",
        title: "It finds similar past bugs",
        body: "It also searches earlier reports by meaning, not exact wording, so the developer sees likely duplicates before saving a new one.",
        plain: "“Freezes” and “hangs” still count as a match.",
        show: ["neighbours"],
      },
      {
        station: "Results",
        title: "Fast and accurate",
        body: "Our goal was an answer in under 5 seconds. On average the rating took 3.4 seconds and the duplicate search 1.2. The model learned from 222,000 real Firefox bug reports, with 20% kept aside for testing.",
        plain: "In the grid, each row is what a bug really was and each column is what the model guessed. The diagonal is every right answer.",
        show: ["timing", "measured"],
      },
      {
        station: "My part",
        title: "My part: design and testing",
        body: "I set the design rules every screen follows, so the app feels like one product whoever built each page. Then I ran a usability test with real users and logged every problem by priority until it was fixed.",
        show: ["usability", "fixes"],
      },
    ] as AnatomyBeat[],
    /** The security step's three risks, in plain words. */
    risks: {
      S: { name: "Fake logins", threat: "A stolen or forged login token", control: "Its signature and expiry are checked, over HTTPS only" },
      I: { name: "Data leaks", threat: "One company seeing another's bugs", control: "Every row of data is locked to its own company" },
      E: { name: "Too much access", threat: "A regular user trying admin actions", control: "The server checks each user's role first" },
    },
    controlLabel: "Protection",
    tokensLabel: "Word scores",
    votesLabel: "Tree votes",
    majority: "Most votes",
    override: "Rule",
    keyword: "Keyword",
    vectorLabel: "Meaning, as numbers",
    timing: { target: "Goal", prediction: "Severity rating", similarity: "Duplicate search", unit: "s" },
    plainLabel: "Put simply",
    measured: {
      scope: "Final presentation: every record scored, training data included",
      metrics: [{ k: "Accuracy", v: "97.6%" }],
      caveat: "That's why it reads higher than the report's 89%: a model always does better on bugs it has already seen.",
      report: { v: "89%", k: "accuracy, final report" },
      actual: "Actual",
      predicted: "Predicted",
      caption: "Confusion matrix, S1 to S4",
      cell: (actual: string, predicted: string, n: string) => `Actually ${actual}, predicted ${predicted}: ${n}`,
      loop: "When an engineer corrects a rating, the correction goes back into training.",
    },
    example2: {
      label: "Example from our final presentation",
      newBug: "New bug",
      matches: "Matches found before it was saved",
      similar: "similar",
    },
    usability: {
      target: "Goal",
      targetText: "A new company admin goes from sign-up to retraining the model in under 8 steps, without being logged out",
      result: "Result",
      status: "Partly met",
      figures: [
        { v: "60%", k: "of tasks finished without a problem" },
        { v: "3.8 / 5", k: "average difficulty" },
      ],
      blockedBy: "What got in the way: testers were logged out twice mid-task, and sign-up created a duplicate admin.",
      priority: { critical: "Critical", high: "High", medium: "Medium", low: "Low" },
      fixes: [
        { problem: "Sign-up created a duplicate admin", priority: "high", fix: "Added a check that stops duplicates", open: false },
        { problem: "Retraining stuck at 0%", priority: "high", fix: "The progress bar now shows real progress", open: false },
        { problem: "Landing-page buttons did nothing", priority: "medium", fix: "Every button now goes where it says", open: false },
        { problem: "A confusing light/dark switch", priority: "low", fix: "Moved to a normal menu in Settings", open: false },
        { problem: "Logged out on the Settings page", priority: "critical", fix: "Traced to the server", open: true },
      ] as { problem: string; priority: "critical" | "high" | "medium" | "low"; fix: string; open: boolean }[],
      fixed: "Fixed",
      open: "Still open when the report was written",
    },
    openCase: "See the Spotfixes project",
  },
  path: {
    aria: "Journey: where I've studied and worked",
    eyebrow: "Where I've been",
    title: "Journey",
    work: "Work",
    education: "Education",
    project: "Project",
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    summer: "Summer",
    summers: "Summers",
    graduated: "Graduated",
    /** City names on the globe (short) and over the record (long). */
    places: { ub: "Ulaanbaatar", erie: "Erie, PA", khanbogd: "Khanbogd" },
    placesLong: { ub: "Ulaanbaatar, Mongolia", erie: "Erie, Pennsylvania, USA" },
    transit: "In transit",
    distance: (km: number) => `≈ ${km.toLocaleString("en-US")} km`,
    board: "Journey log",
    hint: "Scroll or ← → to travel",
    goTo: (title: string) => `Show ${title}`,
    gpaRecent: "GPA · final 4 terms",
    gpaOverall: "GPA · overall",
    coursework: "Coursework",
    moreCourses: (n: number) => `+${n} more`,
    /** The flight row's date: the month the next entry begins. */
    flightDate: (month: string, year: number) => `${month} ${year}`,
    openCase: "Spotfixes case file",
    freight: "Freight between the Ulaanbaatar HQ and the mine site",
    now: "Now",
    /** The landing photos (lib/pathPhotos). Captions name only what the
        picture itself shows. */
    photos: {
      must: {
        caption: "MUST · Building VI",
        alt: "The orange-and-white Building VI of the Mongolian University of Science and Technology under a blue sky in Ulaanbaatar.",
      },
      gannon: {
        caption: "Gannon University · Erie",
        alt: "A red-stone Gannon University building behind the GANNON sign and three flags in Erie.",
      },
      chickfila: {
        caption: "Chick-fil-A · on campus",
        alt: "The Chick-fil-A cow in a red jersey outside the campus Chick-fil-A in the snow.",
      },
      zurn: {
        caption: "Zurn Science Center · Gannon",
        alt: "Zurn Science Center at Gannon University, with an autumn tree in front.",
      },
      victor: {
        caption: "Victor · Gannon's mascot",
        alt: "Victor, Gannon's golden-knight mascot, holding a sword and a pom-pom on the football field.",
      },
      monnis: {
        caption: "Monnis Tower · Ulaanbaatar",
        alt: "The glass Monnis Tower in Ulaanbaatar against a blue sky.",
      },
    },
  },
  caseFile: {
    label: "Case file",
    close: "Close case file",
    overview: "Overview",
    outcomes: "Key outcomes",
    stack: "Stack",
    metrics: "Metrics",
    links: "Links",
    gallery: "Gallery",
    role: "Role",
    year: "Year",
    category: "Category",
    status: "Status",
    prev: "Previous",
    next: "Next",
    esc: "Esc to close",
    /** The case file's reading rail, and the card at its foot. */
    contents: "Contents",
    nextFile: "Next file",
  },
  contact: {
    aria: "Contact",
    title: "Get in touch",
    email: "Email",
    availability: "Availability",
    based: "Based",
    response: "Response",
    responseTime: "Within 48 hours",
    emailMe: "Email me",
    copy: "Copy",
    copied: "Copied",
    copiedLive: (email: string) => `${email} copied to the clipboard`,
    /** The status board beside the address. */
    board: "Status board",
    localTime: "Local time",
  },
  footer: {
    aria: "Footer",
    /* Not "Index": the column's first link is the Index chapter. */
    index: "Contents",
    elsewhere: "Elsewhere",
    top: "Top",
    replay: "Replay intro",
    /** The end credits. Every name here is a fact about how the site was made. */
    credits: {
      title: "Credits",
      design: "Design & code",
      type: "Type",
      built: "Built with",
      footage: "Footage",
      ground: "Rain",
      map: "Map data",
      base: "Made in",
      via: "via",
    },
    /** Trademark credit for the marks on the Signal panels (see BrandMarks) and the Path (see OrgMark). */
    credit:
      "GitHub and the Invertocat logo are trademarks of GitHub, Inc. LinkedIn and the IN logo are registered trademarks of LinkedIn Corporation. The Gannon University, Mongolian University of Science and Technology, Chick-fil-A and Oyu Tolgoi logos belong to their owners and mark where I studied and worked; no endorsement is implied. The photographs on the Journey belong to their owners. Tool logos in the Skills dock are trademarks of their owners.",
  },
  diagnostics: {
    title: "Diagnostics",
    fps: "Frame rate",
    reel: "Ground",
    renderer: "Renderer",
    quality: "Quality",
    dpr: "Pixel ratio",
    viewport: "Viewport",
    locale: "Locale",
    motion: "Motion",
    full: "Full",
    reduced: "Reduced",
    leds: "Intro ink",
    none: "None",
  },
  palette: {
    aria: "Command palette",
    placeholder: "Jump to a section, a case file, or an action…",
    search: "Search commands",
    results: "Commands",
    sections: "Sections",
    caseFiles: "Case files",
    actions: "Actions",
    copyEmail: "Copy email address",
    copiedEmail: "Copied",
    lowPower: "Low-power mode",
    diagnostics: "Diagnostics",
    replay: "Replay the intro",
    rewrite: "Rewrite the neon signs",
    language: "Монгол хэлээр үзэх",
    on: "ON",
    off: "OFF",
    none: (q: string) => `Nothing matches “${q}”.`,
    keys: "↑↓ move · ↵ select · esc close",
    count: (n: number) => `${n} results`,
  },
  common: {
    newTab: "(opens in a new tab)",
    /** The cursor's label over a written neon sign: click and it writes again. */
    rewrite: "REWRITE",
  },
  notFound: {
    eyebrow: "Page not found",
    body: "This page doesn't exist — or it did, and doesn't any more.",
    back: "Back to the index",
  },
};

export type UiStrings = typeof en;

/**
 * Монгол. Draft for Amartuvshin to proofread — see the note in content.mn.ts.
 * Nav-scale labels are kept short on purpose: Mongolian runs longer than
 * English, and the navbar and the rail have fixed room.
 */
const mn: UiStrings = {
  lang: {
    en: "EN",
    mn: "МН",
    switchTo: "Хэл сонгох",
    current: "Монгол",
  },
  preloader: {
    loading: "АЧААЛЖ БАЙНА",
    writing: "БИЧИЖ БАЙНА",
    ready: "БЭЛЭН",
    reel: "ХУУРЦАГ 01 · УЛААНБААТАР",
    skipKey: "Алгасах бол дурын товч дарна уу",
    skipTap: "Алгасах бол товшино уу",
  },
  nav: {
    openMenu: "Цэс нээх",
    closeMenu: "Цэс хаах",
    siteMenu: "Сайтын цэс",
    backToTop: "дээш буцах",
    home: "нүүр",
    index: "Гарчиг",
  },
  hero: {
    aria: "Танилцуулга",
    currently: "Одоо",
    scroll: "Гүйлгэх",
  },
  about: {
    aria: "Танилцуулга",
    languages: "Хэл",
    languagesValue: "Монгол · Англи",
    status: "Төлөв",
    file: "Хувийн хэрэг",
  },
  connect: {
    aria: "Бусад сувгууд",
    eyebrow: "Бусад сувгууд",
    title: "Холбоосууд",
    lead: "Код, ажлын туршлага, ажиллаж буй бүтээгдэхүүн.",
    openProfile: "Профайл нээх",
    openSite: "Сайт нээх",
    repos: (n: number) => `${n} нээлттэй репо`,
    lastPush: "Сүүлд шинэчилсэн",
    live: "Ажиллаж байна",
    recent: "Сүүлд шинэчилсэн",
    copy: (label: string) => `${label} холбоосыг хуулах`,
    copied: "Хуулсан",
    copyShort: "Холбоос хуулах",
    langMix: "Хэлний харьцаа",
    repoLog: "Репогийн түүх",
    started: (name: string, when: string) => `${name}, ${when}-д эхэлсэн`,
    status: "Төлөв",
  },
  work: {
    aria: "Сонгосон төслүүд",
    eyebrow: "Сонгосон төслүүд",
    title: "Төслүүд",
    open: "Дэлгэрэнгүй",
    view: "ҮЗЭХ",
    visit: "Сайт үзэх",
    prev: "Өмнөх төсөл",
    next: "Дараах төсөл",
    rail: "Төслүүд",
    hint: "Гүйлгэх, эсвэл ← →",
    count: (i: number, n: number) => `${String(i).padStart(2, "0")} / ${String(n).padStart(2, "0")}`,
    noSite: "Нээлттэй хувилбаргүй",
    preview: (title: string) => `${title} — дэлгэрэнгүй нээх`,
  },
  craft: {
    aria: "Ур чадвар",
    eyebrow: "Юу хийдэг вэ",
    title: "Ур чадвар",
    lead: "Миний ашигладаг хэрэгслүүд, тус бүрийг хаана хэрэгжүүлснийг харуулав.",
    proven: "Хэрэгжүүлсэн",
    stack: "Хэрэгсэл",
    dock: "Технологийн стек",
    studied: "Ганнонд судалсан",
    degree: (credits: number, deans: number) =>
      `Програм хангамжийн инженерчлэлийн бакалавр · ${credits} кредит · Деканы жагсаалт ×${deans}`,
    hint: "Үргэлжлүүлэн гүйлгэнэ үү",
    tools: {
      usability: "Хэрэглэгчийн туршилт",
      accessibility: "Хүртээмж",
      testcases: "Тест кейс",
      defects: "Алдааны хяналт",
      sdlc: "SDLC",
    },
  },
  anatomy: {
    aria: "Spotfixes хэрхэн ажилладаг вэ: алдааны тайлангаас ноцтой байдлын үнэлгээ хүртэл",
    eyebrow: "Төгсөлтийн төсөл · 3 хүний баг",
    title: "Spotfixes хэрхэн ажилладаг вэ",
    credit: "Миний хэсэг: UI/UX ахлагч, туршилт",
    source: "Төслийн эцсийн тайлан дээр үндэслэв, 2026 оны хавар",
    hint: "Гүйлгэх эсвэл ← → товч",
    step: (i: number, n: number) => `${String(i).padStart(2, "0")} / ${String(n).padStart(2, "0")}`,
    goTo: (title: string) => `Харах: ${title}`,
    illustrative: "Жишээ",
    exampleLabel: "Жишээ тайлан",
    beats: [
      {
        station: "Тайлан",
        title: "Алдааны тайлан ирнэ",
        body: "Хөгжүүлэгч юу буруу болсныг товч бичихэд Spotfixes үүнийг шалгуулахаар сервер рүү илгээнэ.",
        show: ["input"],
      },
      {
        station: "Хамгаалалт",
        title: "Хэн асууж байгааг шалгана",
        body: "Хүсэлт бүр гарын үсэгтэй нэвтрэх токентой ирэх бөгөөд сервер хуурамч эсвэл хугацаа нь дууссаныг буцаана. Компани бүр зөвхөн өөрийн алдааг хардаг.",
        plain: "Орон сууцны байр гэж бодоорой: компани бүр өөрийн хаалгатай, хэн ч өөр хүний айлд орж чадахгүй.",
        show: ["access"],
      },
      {
        station: "Ноцтой байдал",
        title: "Алдаа хэр ноцтойг үнэлнэ",
        body: "Машин сургалтын загвар үг бүрийг оноожуулж, хэдэн зуун жижиг шийдвэрийн мод S1 (хамгийн ноцтой)-ээс S4 хүртэл санал өгнө. “crash”, “security”, “leak” зэрэг үг байвал үргэлж S1 болно.",
        plain: "Загвар англи хэл уншиж чадахгүй тул үг бүр хэр чухал вэ гэдгээр оноо авна: “crash” өндөр, “the” тэг.",
        show: ["forest", "override"],
      },
      {
        station: "Давхардал",
        title: "Төстэй хуучин алдааг олно",
        body: "Мөн өмнөх тайлангуудаас яг ижил үгээр биш, утгаар нь хайдаг тул хөгжүүлэгч шинээр хадгалахаасаа өмнө давхардлыг харна.",
        plain: "“Freezes”, “hangs” хоёр ч таарна.",
        show: ["neighbours"],
      },
      {
        station: "Үр дүн",
        title: "Хурдан бөгөөд оновчтой",
        body: "Зорилго маань 5 секундээс бага хугацаанд хариу өгөх байв. Дунджаар үнэлгээ 3.4, давхардлын хайлт 1.2 секунд зарцуулсан. Загвар Firefox-ийн 222,000 бодит алдаанаас суралцаж, 20%-ийг нь туршилтад үлдээсэн.",
        plain: "Хүснэгтийн мөр бүр алдааны бодит ангилал, багана бүр загварын таамаг. Диагональ дээрх бүхэн зөв хариулт.",
        show: ["timing", "measured"],
      },
      {
        station: "Миний хэсэг",
        title: "Миний хэсэг: дизайн ба туршилт",
        body: "Дэлгэц бүрийн дагах дизайны дүрмийг би тогтоосон тул хуудас бүрийг хэн хийснээс үл хамааран апп нэг бүтээгдэхүүн мэт харагдана. Дараа нь бодит хэрэглэгчидтэй туршилт хийж, асуудал бүрийг засагдтал ач холбогдлоор нь бүртгэсэн.",
        show: ["usability", "fixes"],
      },
    ] as AnatomyBeat[],
    risks: {
      S: { name: "Хуурамч нэвтрэлт", threat: "Хулгайлсан эсвэл хуурамч токен", control: "Гарын үсэг, хугацааг зөвхөн HTTPS-ээр шалгана" },
      I: { name: "Өгөгдөл алдагдах", threat: "Нэг компани нөгөөгийнхөө алдааг харах", control: "Өгөгдлийн мөр бүр өөрийн компанид түгжигдсэн" },
      E: { name: "Илүү эрх", threat: "Энгийн хэрэглэгч админы үйлдэл хийх", control: "Сервер хэрэглэгчийн үүргийг эхлээд шалгана" },
    },
    controlLabel: "Хамгаалалт",
    tokensLabel: "Үгийн оноо",
    votesLabel: "Модны санал",
    majority: "Олонх",
    override: "Дүрэм",
    keyword: "Түлхүүр үг",
    vectorLabel: "Утга, тоогоор",
    timing: { target: "Зорилго", prediction: "Ноцтой байдлын үнэлгээ", similarity: "Давхардлын хайлт", unit: "с" },
    plainLabel: "Энгийнээр",
    measured: {
      scope: "Эцсийн танилцуулга: бүх бичлэгийг сургалтын өгөгдлийн хамт үнэлсэн",
      metrics: [{ k: "Нарийвчлал", v: "97.6%" }],
      caveat: "Тиймээс тайлангийн 89%-иас өндөр харагдана: загвар өмнө нь харсан алдаан дээрээ үргэлж илүү сайн.",
      report: { v: "89%", k: "нарийвчлал, эцсийн тайлан" },
      actual: "Бодит",
      predicted: "Таамагласан",
      caption: "Төөрөгдлийн матриц, S1-ээс S4",
      cell: (actual: string, predicted: string, n: string) => `Бодит ${actual}, таамагласан ${predicted}: ${n}`,
      loop: "Инженер үнэлгээг засахад тэр засвар сургалт руу буцаж орно.",
    },
    example2: {
      label: "Эцсийн танилцуулгаас авсан жишээ",
      newBug: "Шинэ алдаа",
      matches: "Хадгалахаас өмнө олдсон тохирол",
      similar: "төстэй",
    },
    usability: {
      target: "Зорилго",
      targetText: "Компанийн шинэ админ бүртгүүлэхээс загвараа дахин сургах хүртэл 8-аас бага алхамд, системээс гарахгүйгээр",
      result: "Үр дүн",
      status: "Хэсэгчлэн биелсэн",
      figures: [
        { v: "60%", k: "даалгаврыг асуудалгүй дуусгасан" },
        { v: "3.8 / 5", k: "дундаж хүндрэл" },
      ],
      blockedBy: "Саад болсон зүйл: туршигчид хоёр удаа системээс гарсан, бүртгэл давхар админ үүсгэсэн.",
      priority: { critical: "Ноцтой", high: "Өндөр", medium: "Дунд", low: "Бага" },
      fixes: [
        { problem: "Бүртгүүлэхэд давхар админ үүсдэг", priority: "high", fix: "Давхардлыг хориглох шалгалт нэмсэн", open: false },
        { problem: "Дахин сургалт 0% дээр гацдаг", priority: "high", fix: "Явцын мөр бодит явцыг харуулдаг болсон", open: false },
        { problem: "Нүүр хуудасны товчлуурууд ажилладаггүй", priority: "medium", fix: "Товч бүр зөв газар руугаа очдог болсон", open: false },
        { problem: "Ойлгомжгүй гэрэл/харанхуй товч", priority: "low", fix: "Тохиргоо доторх энгийн цэс рүү зөөсөн", open: false },
        { problem: "Тохиргооны хуудсанд системээс гардаг", priority: "critical", fix: "Сервер талаас эх үүсвэрийг олсон", open: true },
      ],
      fixed: "Засагдсан",
      open: "Тайлан бичих үед засагдаагүй байсан",
    },
    openCase: "Spotfixes төслийг үзэх",
  },
  path: {
    aria: "Замнал: суралцаж, ажилласан газрууд",
    eyebrow: "Туулсан зам",
    title: "Замнал",
    work: "Ажил",
    education: "Боловсрол",
    project: "Төсөл",
    /* Mongolian months are ordinal ("6-р сар", "the 6th month"); the ordinal
       suffix is the same for all twelve. */
    months: Array.from({ length: 12 }, (_, i) => `${i + 1}-р сар`),
    summer: "Зун",
    summers: "Зун",
    graduated: "Төгссөн",
    places: { ub: "Улаанбаатар", erie: "Эри, Пенсильвани", khanbogd: "Ханбогд" },
    placesLong: { ub: "Улаанбаатар, Монгол", erie: "Эри, Пенсильвани, АНУ" },
    transit: "Замд",
    distance: (km: number) => `≈ ${km.toLocaleString("mn-MN")} км`,
    board: "Замналын бүртгэл",
    hint: "Гүйлгэх эсвэл ← → товчоор аялах",
    goTo: (title: string) => `${title} — харах`,
    gpaRecent: "Голч · сүүлийн 4 улирал",
    gpaOverall: "Голч · нийт",
    coursework: "Судалсан хичээлүүд",
    moreCourses: (n: number) => `+${n} хичээл`,
    flightDate: (month: string, year: number) => `${year} оны ${month}`,
    openCase: "Spotfixes — дэлгэрэнгүй",
    freight: "Төв оффис болон уурхайн хоорондын ачаа тээвэр",
    now: "Одоо",
    /* Drafts: awaiting Amartuvshin's proofread. */
    photos: {
      must: {
        caption: "ШУТИС · VI байр",
        alt: "Цэнхэр тэнгэрийн дор ШУТИС-ийн улбар шар, цагаан өнгөтэй VI байр, Улаанбаатар.",
      },
      gannon: {
        caption: "Gannon их сургууль · Эри",
        alt: "GANNON самбар, гурван тугны ард Gannon их сургуулийн улаан чулуун барилга, Эри.",
      },
      chickfila: {
        caption: "Chick-fil-A · оюутны хотхонд",
        alt: "Цасан дунд, оюутны хотхоны Chick-fil-A-ийн үүдэнд улаан өмсгөлтэй Chick-fil-A үнээ.",
      },
      zurn: {
        caption: "Zurn Science Center · Gannon",
        alt: "Gannon их сургуулийн Zurn Science Center, урд нь намрын мод.",
      },
      victor: {
        caption: "Victor · Gannon-ий сахиус",
        alt: "Gannon-ий алтан баатар сахиус Victor хөлбөмбөгийн талбай дээр сэлэм, помпон барьж байна.",
      },
      monnis: {
        caption: "Monnis Tower · Улаанбаатар",
        alt: "Цэнхэр тэнгэрийн дор Улаанбаатар дахь шилэн Monnis Tower.",
      },
    },
  },
  caseFile: {
    label: "Төслийн дэлгэрэнгүй",
    close: "Хаах",
    overview: "Тойм",
    outcomes: "Гол үр дүн",
    stack: "Технологи",
    metrics: "Үзүүлэлт",
    links: "Холбоос",
    gallery: "Зургууд",
    role: "Үүрэг",
    year: "Он",
    category: "Төрөл",
    status: "Төлөв",
    prev: "Өмнөх",
    next: "Дараах",
    esc: "Esc — хаах",
    contents: "Агуулга",
    nextFile: "Дараагийн төсөл",
  },
  contact: {
    aria: "Холбогдох",
    title: "Холбоо барих",
    email: "И-мэйл",
    availability: "Боломж",
    based: "Байршил",
    response: "Хариу",
    responseTime: "48 цагийн дотор",
    emailMe: "И-мэйл бичих",
    copy: "Хуулах",
    copied: "Хуулсан",
    copiedLive: (email: string) => `${email} хаягийг хуулсан`,
    board: "Төлөвийн самбар",
    localTime: "Орон нутгийн цаг",
  },
  footer: {
    aria: "Хөл хэсэг",
    index: "Агуулга",
    elsewhere: "Бусад",
    top: "Дээш",
    replay: "Эхлэлийг дахин үзэх",
    credits: {
      title: "Титр",
      design: "Дизайн ба код",
      type: "Үсгийн хэв",
      built: "Ашигласан технологи",
      footage: "Видео бичлэг",
      ground: "Бороо",
      map: "Газрын зургийн өгөгдөл",
      base: "Бүтээсэн газар",
      via: "эх сурвалж",
    },
    credit:
      "GitHub болон Invertocat лого нь GitHub, Inc.-ийн барааны тэмдэг. LinkedIn болон IN лого нь LinkedIn Corporation-ийн бүртгэлтэй барааны тэмдэг. Gannon University, ШУТИС, Chick-fil-A, Оюу Толгойн лого нь эзэмшигчдийнх бөгөөд миний суралцаж, ажилласан газрыг заана; ямар нэг дэмжлэг илэрхийлээгүй. Замнал хэсгийн гэрэл зургууд эзэмшигчдийнх. Ур чадвар хэсгийн хэрэгслийн логонууд эзэмшигчдийнх нь барааны тэмдэг.",
  },
  diagnostics: {
    title: "Оношилгоо",
    fps: "Кадрын давтамж",
    reel: "Дэвсгэр",
    renderer: "Рендерер",
    quality: "Чанар",
    dpr: "Пикселийн харьцаа",
    viewport: "Дэлгэц",
    locale: "Хэл",
    motion: "Хөдөлгөөн",
    full: "Бүрэн",
    reduced: "Багасгасан",
    leds: "Интро бэх",
    none: "Байхгүй",
  },
  palette: {
    aria: "Командын цонх",
    placeholder: "Хэсэг, төсөл эсвэл үйлдэл хайх…",
    search: "Команд хайх",
    results: "Командууд",
    sections: "Хэсгүүд",
    caseFiles: "Төслүүд",
    actions: "Үйлдлүүд",
    copyEmail: "И-мэйл хаяг хуулах",
    copiedEmail: "Хуулагдлаа",
    lowPower: "Хэмнэлттэй горим",
    diagnostics: "Оношилгоо",
    replay: "Эхлэлийг дахин үзэх",
    rewrite: "Неон самбаруудыг дахин бичих",
    language: "View in English",
    on: "ИДЭВХТЭЙ",
    off: "ИДЭВХГҮЙ",
    none: (q: string) => `“${q}”-д тохирох зүйл алга.`,
    keys: "↑↓ шилжих · ↵ сонгох · esc хаах",
    count: (n: number) => `${n} илэрц`,
  },
  common: {
    newTab: "(шинэ цонхонд нээгдэнэ)",
    rewrite: "ДАХИН БИЧИХ",
  },
  notFound: {
    eyebrow: "Хуудас олдсонгүй",
    body: "Энэ хуудас байхгүй — эсвэл байсан ч одоо алга.",
    back: "Нүүр хуудас руу буцах",
  },
};

export const ui: { en: UiStrings; mn?: UiStrings } = { en, mn };
