/**
 * Interface strings — everything a component used to hard-code.
 *
 * Content (who he is, what he built) lives in `content.ts`; this is the frame
 * around it: labels, buttons, form messages, aria text. Kept separate because it
 * changes for different reasons — copy is edited when his story changes, this
 * when the interface does.
 *
 * `UiStrings` is inferred from the English table, so the Mongolian table is
 * checked key-for-key against it: a string added here and not translated is a
 * type error, not a silent English fallback.
 */

const en = {
  lang: {
    /** The toggle's own labels, always in their own script. */
    en: "EN",
    mn: "МН",
    switchTo: "Switch language",
    current: "English",
  },
  preloader: {
    loading: "LOADING",
    writing: "WRITING",
    ready: "READY",
    /** The slate in the intro's top bar. */
    reel: "REEL 01 · ULAANBAATAR",
    skipKey: "Press any key to skip",
    skipTap: "Tap to skip",
  },
  nav: {
    openMenu: "Open menu",
    closeMenu: "Close menu",
    siteMenu: "Site menu",
    backToTop: "back to top",
    home: "home",
    /** The phone's menu button, visible text. */
    index: "Index",
  },
  hero: {
    aria: "Introduction",
    currently: "Currently",
    scroll: "Scroll",
  },
  about: {
    aria: "Profile",
    /** The dossier plate's extra fields. Both facts are already in the About
     *  copy ("fluent in Mongolian and English") and the hero status. */
    languages: "Languages",
    languagesValue: "Mongolian · English",
    status: "Status",
    file: "Personnel file",
  },
  connect: {
    aria: "Find me elsewhere",
    eyebrow: "Find me elsewhere",
    title: "Signal",
    lead: "The code, the career history, and the live product.",
    openProfile: "Open profile",
    openSite: "Open live site",
    repos: (n: number) => `${n} public repos`,
    lastPush: "Last push",
    /** The live product's lamp in its panel readout. */
    live: "Live",
    recent: "Recently pushed",
    /** The tuner band over the three channels. */
    tuner: "Channel tuner",
    scanning: "Scanning",
    tuned: "Tuned",
    tuneHint: "← → to tune",
    langMix: "Language mix",
    repoLog: "Repo log",
    started: (name: string, when: string) => `${name}, started ${when}`,
    status: "Status",
  },
  work: {
    aria: "Selected work",
    eyebrow: "Selected work",
    title: "Work",
    open: "Open case file",
    /** The cursor's label over a case file you can open. */
    view: "VIEW",
    visit: "Visit site",
    prev: "Previous case file",
    next: "Next case file",
    rail: "Case files",
    hint: "Scroll, or use ← →",
    count: (i: number, n: number) => `${String(i).padStart(2, "0")} / ${String(n).padStart(2, "0")}`,
    noSite: "No public build",
    preview: (title: string) => `${title} — open case file`,
  },
  craft: {
    aria: "Capabilities",
    eyebrow: "What I do",
    title: "Craft",
    lead: "What I reach for, and where each one has been put to work.",
    proven: "Proven in",
    stack: "Tools",
    hint: "Keep scrolling",
    tools: {
      usability: "Usability testing",
      accessibility: "Accessibility",
      testcases: "Test cases",
      defects: "Defect tracking",
      sdlc: "SDLC",
    },
  },
  anatomy: {
    aria: "Inside Spotfixes: how one bug report becomes a severity prediction",
    eyebrow: "Spotfixes · team capstone",
    title: "Anatomy of a prediction",
    credit: "Team of 3 · my part: UI/UX lead and QA",
    source: "From our final capstone report, Spring 2026",
    hint: "Scroll or ← → to follow it",
    step: (i: number, n: number) => `${String(i).padStart(2, "0")} / ${String(n).padStart(2, "0")}`,
    goTo: (title: string) => `Show: ${title}`,
    illustrative: "Illustrative",
    exampleLabel: "Example input",
    nodes: {
      input: "Analysis tab",
      api: "FastAPI",
      guard: "Tenant Guard",
      db: "Supabase · RLS",
      tfidf: "TF-IDF",
      forest: "Random Forest",
      rules: "Rule engine",
      embed: "MiniLM",
      chroma: "ChromaDB",
      result: "Result",
    },
    nodeSubs: {
      input: "React UI",
      api: "/analyze_bug",
      guard: "company_id from token",
      db: "row-level security",
      tfidf: "tfidf_vectorizer.pkl",
      forest: "rf_model.pkl",
      rules: "critical keywords",
      embed: "all-MiniLM-L6-v2",
      chroma: "top 3 · cosine",
      result: "React UI",
    },
    myPart: "My part",
    boundary1: "Trust boundary · client → API",
    boundary2: "Trust boundary · API → database",
    beats: [
      {
        title: "A report comes in",
        body: "A developer pastes a bug summary into the Analysis tab. The React front end sends it to the FastAPI back end as a POST to /analyze_bug.",
      },
      {
        title: "Who is asking?",
        body: "Every request carries a JSON Web Token. Before anything else runs, the API checks its signature and expiry, over HTTPS only. This is the first trust boundary, so it is where the threat model starts.",
      },
      {
        title: "Whose data is this?",
        body: "Companies share one system but never see each other's bugs. The Tenant Guard takes the company ID from the verified token, never from the request, and Supabase row-level security enforces the same rule again inside the database.",
      },
      {
        title: "The forest votes",
        body: "The summary becomes TF-IDF word weights, and the trees of a Random Forest vote on its severity, from S1 (most severe) to S4. The model's probability becomes the confidence score.",
      },
      {
        title: "A word that overrides",
        body: "A rule engine then looks for critical keywords such as “crash”, “security” and “leak”. If one is there, the label is forced to S1, so a dangerous bug never sinks to the bottom of the pile.",
      },
      {
        title: "Seen this before?",
        body: "Alongside the forest, a sentence-transformer model turns the summary into a vector, and ChromaDB finds the three past reports closest to it by cosine distance, shown as a similarity match.",
      },
      {
        title: "An answer in under five seconds",
        body: "The UI shows the severity, the confidence, the keywords behind it, a suggested team and the three similar reports. The target was under 5 s; the measured averages were 3.4 s for the prediction and 1.2 s for the similarity search.",
      },
      {
        title: "What we didn't build",
        body: "Three designs we weighed and turned down, and why.",
      },
      {
        title: "Then I put it in front of people",
        body: "As UI/UX lead I ran the usability testing and kept the QA log. One session, measured against a target we had set ourselves:",
      },
    ],
    stride: {
      S: "Spoofing",
      T: "Tampering",
      R: "Repudiation",
      I: "Information disclosure",
      D: "Denial of service",
      E: "Elevation of privilege",
    },
    threats: {
      S: { threat: "A stolen or forged token", control: "JWT signature and expiry checks, HTTPS only" },
      D: { threat: "Flooding the API with heavy queries", control: "Rate limits, input size limits, timeouts, top-k caps" },
      T: { threat: "A request rewriting its company scope", control: "company_id from the token, the Tenant Guard, RLS" },
      I: { threat: "One company seeing another's bugs", control: "RLS and tenant-scoped queries" },
      E: { threat: "A viewer running admin actions", control: "Role checks on the server (memberships.role)" },
      R: { threat: "Denying a submit, import or retrain", control: "audit_logs: actor, action, target, time" },
    },
    threatLabel: "Threat",
    controlLabel: "Control",
    tokensLabel: "TF-IDF weights",
    votesLabel: "Tree votes",
    majority: "Majority",
    override: "Override",
    keyword: "Keyword",
    vectorLabel: "Vector",
    neighbours: "3 nearest past reports",
    pastReport: (n: number) => `Past report ${n}`,
    result: {
      severity: "Severity",
      confidence: "Confidence",
      confidenceValue: "from the model's probability",
      keywords: "Keywords",
      team: "Suggested team",
      similar: "Similar reports",
    },
    timing: { target: "Target", prediction: "Prediction", similarity: "Similarity search", unit: "s", avg: "avg" },
    extras: [
      { v: "89%", k: "model accuracy" },
      { v: "100 in 42 s", k: "records per bulk upload, no timeout" },
    ],
    notChosen: "Not chosen",
    alternatives: [
      {
        name: "Ask an LLM directly",
        why: "A simpler pipeline, but it needs far more computing power and costs much more to run than the hybrid.",
      },
      {
        name: "Streamlit only",
        why: "Our first prototype: quick to build, but too slow for a live demo and too limited to design.",
      },
      {
        name: "One shared database",
        why: "Simpler queries, but the requirements called for strict isolation between companies.",
      },
    ],
    usability: {
      target: "Target",
      targetText: "A new company admin, sign-up to model retraining in under 8 actions, without the session dropping",
      result: "Result",
      status: "Partially met",
      figures: [
        { v: "60%", k: "of tasks completed without failure" },
        { v: "3.8 / 5", k: "average difficulty" },
      ],
      blockedBy:
        "What got in the way: the session dropped, forcing two extra logins, and sign-up created a duplicate admin.",
      fixesLabel: "What the log turned into",
      priority: { critical: "Critical", high: "High", medium: "Medium", low: "Low" },
      fixes: [
        { problem: "Sign-up created a duplicate admin", priority: "high", fix: "Unique-constraint checks in the onboarding hook", open: false },
        { problem: "Retraining stuck at 0%", priority: "high", fix: "The API polls the real epoch progress", open: false },
        { problem: "Landing-page buttons did nothing", priority: "medium", fix: "Every button routed to its module", open: false },
        { problem: "Experimental light/dark toggle", priority: "low", fix: "A standard menu in Settings", open: false },
        { problem: "Session dropped on the settings page", priority: "critical", fix: "Back-end debugging", open: true },
      ] as { problem: string; priority: "critical" | "high" | "medium" | "low"; fix: string; open: boolean }[],
      fixed: "Fixed",
      open: "In progress at the time of the report",
    },
    openCase: "Spotfixes case file",
  },
  path: {
    aria: "Path: where I've studied and worked",
    eyebrow: "Where I've been",
    title: "Path",
    work: "Work",
    education: "Education",
    project: "Project",
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    summer: "Summer",
    graduated: "Graduated",
    /** City names on the globe (short) and over the record (long). */
    places: { ub: "Ulaanbaatar", erie: "Erie, PA", khanbogd: "Khanbogd" },
    placesLong: { ub: "Ulaanbaatar, Mongolia", erie: "Erie, Pennsylvania, USA" },
    transit: "In transit",
    distance: (km: number) => `≈ ${km.toLocaleString("en-US")} km`,
    board: "Route log",
    hint: "Scroll or ← → to travel",
    goTo: (title: string) => `Show ${title}`,
    gpa: "GPA, final four semesters",
    openCase: "Spotfixes case file",
    freight: "Freight between the Ulaanbaatar HQ and the mine site",
    now: "Now",
  },
  caseFile: {
    label: "Case file",
    close: "Close case file",
    overview: "Overview",
    outcomes: "Key outcomes",
    stack: "Stack",
    metrics: "Metrics",
    links: "Links",
    gallery: "Gallery",
    role: "Role",
    year: "Year",
    category: "Category",
    status: "Status",
    prev: "Previous",
    next: "Next",
    esc: "Esc to close",
    /** The case file's reading rail, and the card at its foot. */
    contents: "Contents",
    nextFile: "Next file",
  },
  contact: {
    aria: "Contact",
    title: "Get in touch",
    email: "Email",
    availability: "Availability",
    based: "Based",
    response: "Response",
    responseTime: "Within 48 hours",
    emailMe: "Email me",
    copy: "Copy",
    copied: "Copied",
    copiedLive: (email: string) => `${email} copied to the clipboard`,
    /** The status board beside the address. */
    board: "Status board",
    localTime: "Local time",
  },
  footer: {
    aria: "Footer",
    /* Not "Index": the column's first link is the Index chapter. */
    index: "Contents",
    elsewhere: "Elsewhere",
    top: "Top",
    replay: "Replay intro",
    /** The end credits. Every name here is a fact about how the site was made. */
    credits: {
      title: "Credits",
      design: "Design & code",
      type: "Type",
      built: "Built with",
      city: "City reel",
      station: "Station reel",
      map: "Map data",
      base: "Made in",
      via: "via",
    },
    /** Trademark credit for the marks on the Signal panels (see BrandMarks). */
    credit:
      "GitHub and the Invertocat logo are trademarks of GitHub, Inc. LinkedIn and the IN logo are registered trademarks of LinkedIn Corporation.",
  },
  diagnostics: {
    title: "Diagnostics",
    fps: "Frame rate",
    reel: "Film",
    renderer: "Renderer",
    quality: "Quality",
    dpr: "Pixel ratio",
    viewport: "Viewport",
    locale: "Locale",
    motion: "Motion",
    full: "Full",
    reduced: "Reduced",
    leds: "Intro ink",
    none: "None",
  },
  palette: {
    aria: "Command palette",
    placeholder: "Jump to a section, a case file, or an action…",
    search: "Search commands",
    results: "Commands",
    sections: "Sections",
    caseFiles: "Case files",
    actions: "Actions",
    copyEmail: "Copy email address",
    copiedEmail: "Copied",
    lowPower: "Low-power mode",
    diagnostics: "Diagnostics",
    replay: "Replay the intro",
    rewrite: "Rewrite the neon signs",
    language: "Монгол хэлээр үзэх",
    on: "ON",
    off: "OFF",
    none: (q: string) => `Nothing matches “${q}”.`,
    keys: "↑↓ move · ↵ select · esc close",
    count: (n: number) => `${n} results`,
  },
  common: {
    newTab: "(opens in a new tab)",
    /** The cursor's label over a written neon sign: click and it writes again. */
    rewrite: "REWRITE",
  },
  notFound: {
    eyebrow: "Page not found",
    body: "This page doesn't exist — or it did, and doesn't any more.",
    back: "Back to the index",
  },
};

export type UiStrings = typeof en;

/**
 * Монгол. Draft for Amartuvshin to proofread — see the note in content.mn.ts.
 * Nav-scale labels are kept short on purpose: Mongolian runs longer than
 * English, and the navbar and the rail have fixed room.
 */
const mn: UiStrings = {
  lang: {
    en: "EN",
    mn: "МН",
    switchTo: "Хэл сонгох",
    current: "Монгол",
  },
  preloader: {
    loading: "АЧААЛЖ БАЙНА",
    writing: "БИЧИЖ БАЙНА",
    ready: "БЭЛЭН",
    reel: "ХУУРЦАГ 01 · УЛААНБААТАР",
    skipKey: "Алгасах бол дурын товч дарна уу",
    skipTap: "Алгасах бол товшино уу",
  },
  nav: {
    openMenu: "Цэс нээх",
    closeMenu: "Цэс хаах",
    siteMenu: "Сайтын цэс",
    backToTop: "дээш буцах",
    home: "нүүр",
    index: "Гарчиг",
  },
  hero: {
    aria: "Танилцуулга",
    currently: "Одоо",
    scroll: "Гүйлгэх",
  },
  about: {
    aria: "Танилцуулга",
    languages: "Хэл",
    languagesValue: "Монгол · Англи",
    status: "Төлөв",
    file: "Хувийн хэрэг",
  },
  connect: {
    aria: "Бусад сувгууд",
    eyebrow: "Бусад сувгууд",
    title: "Холбоо",
    lead: "Код, ажлын туршлага, ажиллаж буй бүтээгдэхүүн.",
    openProfile: "Профайл нээх",
    openSite: "Сайт нээх",
    repos: (n: number) => `${n} нээлттэй репо`,
    lastPush: "Сүүлд шинэчилсэн",
    live: "Ажиллаж байна",
    recent: "Сүүлд шинэчилсэн",
    tuner: "Суваг тааруулагч",
    scanning: "Хайж байна",
    tuned: "Тааруулсан",
    tuneHint: "← → сонгох",
    langMix: "Хэлний харьцаа",
    repoLog: "Репогийн түүх",
    started: (name: string, when: string) => `${name}, ${when}-д эхэлсэн`,
    status: "Төлөв",
  },
  work: {
    aria: "Сонгосон төслүүд",
    eyebrow: "Сонгосон төслүүд",
    title: "Төслүүд",
    open: "Дэлгэрэнгүй",
    view: "ҮЗЭХ",
    visit: "Сайт үзэх",
    prev: "Өмнөх төсөл",
    next: "Дараах төсөл",
    rail: "Төслүүд",
    hint: "Гүйлгэх, эсвэл ← →",
    count: (i: number, n: number) => `${String(i).padStart(2, "0")} / ${String(n).padStart(2, "0")}`,
    noSite: "Нээлттэй хувилбаргүй",
    preview: (title: string) => `${title} — дэлгэрэнгүй нээх`,
  },
  craft: {
    aria: "Ур чадвар",
    eyebrow: "Юу хийдэг вэ",
    title: "Ур чадвар",
    lead: "Миний ашигладаг хэрэгслүүд, тус бүрийг хаана хэрэгжүүлснийг харуулав.",
    proven: "Хэрэгжүүлсэн",
    stack: "Хэрэгсэл",
    hint: "Үргэлжлүүлэн гүйлгэнэ үү",
    tools: {
      usability: "Хэрэглэгчийн туршилт",
      accessibility: "Хүртээмж",
      testcases: "Тест кейс",
      defects: "Алдааны хяналт",
      sdlc: "SDLC",
    },
  },
  anatomy: {
    aria: "Spotfixes-ийн дотор: алдааны тайлан хэрхэн ноцтой байдлын таамаглал болдог вэ",
    eyebrow: "Spotfixes · багийн дипломын төсөл",
    title: "Таамаглалын бүтэц",
    credit: "3 хүний баг · миний хэсэг: UI/UX ахлагч, QA",
    source: "Манай дипломын төслийн эцсийн тайлангаас, 2026 оны хавар",
    hint: "Гүйлгэх эсвэл ← → дарж дагаарай",
    step: (i: number, n: number) => `${String(i).padStart(2, "0")} / ${String(n).padStart(2, "0")}`,
    goTo: (title: string) => `Харах: ${title}`,
    illustrative: "Жишээ дүрслэл",
    exampleLabel: "Жишээ оролт",
    nodes: {
      input: "Шинжилгээний таб",
      api: "FastAPI",
      guard: "Tenant Guard",
      db: "Supabase · RLS",
      tfidf: "TF-IDF",
      forest: "Random Forest",
      rules: "Дүрмийн хөдөлгүүр",
      embed: "MiniLM",
      chroma: "ChromaDB",
      result: "Үр дүн",
    },
    nodeSubs: {
      input: "React UI",
      api: "/analyze_bug",
      guard: "company_id токеноос",
      db: "мөрийн түвшний хамгаалалт",
      tfidf: "tfidf_vectorizer.pkl",
      forest: "rf_model.pkl",
      rules: "чухал түлхүүр үгс",
      embed: "all-MiniLM-L6-v2",
      chroma: "ойрын 3 · косинус",
      result: "React UI",
    },
    myPart: "Миний хэсэг",
    boundary1: "Итгэлцлийн хил · клиент → API",
    boundary2: "Итгэлцлийн хил · API → өгөгдлийн сан",
    beats: [
      {
        title: "Тайлан ирлээ",
        body: "Хөгжүүлэгч алдааны товч тайлбарыг Шинжилгээний табад оруулна. React интерфейс үүнийг FastAPI сервер рүү /analyze_bug хаягаар POST хүсэлтээр илгээнэ.",
      },
      {
        title: "Хэн асууж байна вэ?",
        body: "Хүсэлт бүр JSON Web Token-той ирнэ. Бусад бүхнээс өмнө API түүний гарын үсэг, хүчинтэй хугацааг зөвхөн HTTPS-ээр шалгана. Энэ бол итгэлцлийн эхний хил тул аюулын загвар эндээс эхэлнэ.",
      },
      {
        title: "Энэ хэний өгөгдөл вэ?",
        body: "Компаниуд нэг системийг хуваалцдаг ч бие биеийнхээ алдааг хэзээ ч хардаггүй. Tenant Guard компанийн дугаарыг хүсэлтээс биш, баталгаажсан токеноос авдаг бөгөөд Supabase-ийн мөрийн түвшний хамгаалалт ижил дүрмийг өгөгдлийн санд дахин мөрдүүлнэ.",
      },
      {
        title: "Ой санал өгнө",
        body: "Товч тайлбар TF-IDF үгсийн жин болж, Random Forest загварын моднууд түүний ноцтой байдлыг S1 (хамгийн ноцтой)-ээс S4 хүртэл санал хураана. Загварын магадлал итгэлийн оноо болно.",
      },
      {
        title: "Шийдвэрийг өөрчлөх үг",
        body: "Дараа нь дүрмийн хөдөлгүүр “crash”, “security”, “leak” зэрэг чухал түлхүүр үгсийг хайна. Аль нэг нь байвал шошгыг S1 болгож, аюултай алдаа жагсаалтын ёроолд живэхээс сэргийлнэ.",
      },
      {
        title: "Өмнө нь тохиолдож байсан уу?",
        body: "Ойтой зэрэгцэн sentence-transformer загвар товч тайлбарыг вектор болгож, ChromaDB косинус зайгаар хамгийн ойр гурван өмнөх тайланг олж, ижил төстэй байдлаар нь харуулна.",
      },
      {
        title: "Таван секунд хүрэхгүй хугацаанд хариу",
        body: "Интерфейс ноцтой байдал, итгэлийн оноо, түүнд нөлөөлсөн түлхүүр үгс, санал болгох баг, ижил төстэй гурван тайланг харуулна. Зорилт 5 секундээс бага байсан; хэмжсэн дундаж нь таамаглалд 3.4 с, ижил төстэй хайлтад 1.2 с.",
      },
      {
        title: "Бидний бүтээгээгүй зүйлс",
        body: "Бидний авч үзээд татгалзсан гурван шийдэл, шалтгааных нь хамт.",
      },
      {
        title: "Дараа нь хүмүүст туршуулсан",
        body: "UI/UX ахлагчийн хувьд би хэрэглэгчийн туршилтыг явуулж, QA бүртгэлийг хөтөлсөн. Нэг туршилт, бидний өөрсдөө тавьсан зорилттой харьцуулбал:",
      },
    ],
    stride: {
      S: "Хуурамчаар илрэх",
      T: "Өөрчлөх",
      R: "Үгүйсгэх",
      I: "Мэдээлэл задрах",
      D: "Үйлчилгээг саатуулах",
      E: "Эрх нэмэгдүүлэх",
    },
    threats: {
      S: { threat: "Хулгайлсан эсвэл хуурамч токен", control: "JWT гарын үсэг, хугацааны шалгалт, зөвхөн HTTPS" },
      D: { threat: "API-г хүнд асуулгаар үерлэх", control: "Хүсэлтийн хязгаар, оролтын хэмжээний хязгаар, хугацаа, top-k хязгаар" },
      T: { threat: "Хүсэлт компанийн хүрээгээ өөрчлөх", control: "company_id токеноос, Tenant Guard, RLS" },
      I: { threat: "Нэг компани нөгөөгийнхөө алдааг харах", control: "RLS ба компанийн хүрээтэй асуулга" },
      E: { threat: "Үзэгч админы үйлдэл хийх", control: "Сервер талын эрхийн шалгалт (memberships.role)" },
      R: { threat: "Илгээсэн, импортолсон, дахин сургасныг үгүйсгэх", control: "audit_logs: хэн, юу, юунд, хэзээ" },
    },
    threatLabel: "Аюул",
    controlLabel: "Хамгаалалт",
    tokensLabel: "TF-IDF жин",
    votesLabel: "Модны санал",
    majority: "Олонх",
    override: "Дарж өөрчилсөн",
    keyword: "Түлхүүр үг",
    vectorLabel: "Вектор",
    neighbours: "Хамгийн ойр 3 өмнөх тайлан",
    pastReport: (n: number) => `Өмнөх тайлан ${n}`,
    result: {
      severity: "Ноцтой байдал",
      confidence: "Итгэл",
      confidenceValue: "загварын магадлалаас",
      keywords: "Түлхүүр үгс",
      team: "Санал болгох баг",
      similar: "Ижил төстэй тайлан",
    },
    timing: { target: "Зорилт", prediction: "Таамаглал", similarity: "Ижил төстэй хайлт", unit: "с", avg: "дундаж" },
    extras: [
      { v: "89%", k: "загварын нарийвчлал" },
      { v: "100 / 42 с", k: "бөөнөөр оруулахад, хугацаа хэтрэхгүй" },
    ],
    notChosen: "Сонгоогүй",
    alternatives: [
      {
        name: "LLM-ээс шууд асуух",
        why: "Шугам энгийн болох ч тооцоолох хүчин чадал хамаагүй их шаардаж, эрлийз шийдлээс хамаагүй үнэтэй.",
      },
      {
        name: "Зөвхөн Streamlit",
        why: "Бидний анхны прототип: хурдан бүтээгддэг ч амьд танилцуулгад удаан, дизайны боломж хязгаарлагдмал.",
      },
      {
        name: "Нэг нийтийн өгөгдлийн сан",
        why: "Асуулга энгийн болох ч шаардлагад компаниудын өгөгдлийг хатуу тусгаарлахыг заасан.",
      },
    ],
    usability: {
      target: "Зорилт",
      targetText: "Компанийн шинэ админ бүртгүүлэхээс загвараа дахин сургах хүртэл 8-аас бага үйлдэлд, сесс тасрахгүйгээр",
      result: "Үр дүн",
      status: "Хэсэгчлэн биелсэн",
      figures: [
        { v: "60%", k: "даалгаврыг алдаагүй гүйцэтгэсэн" },
        { v: "3.8 / 5", k: "дундаж хүндрэл" },
      ],
      blockedBy:
        "Саад болсон зүйл: сесс тасарч хоёр удаа дахин нэвтрэхэд хүргэсэн, бүртгэл давхар админ үүсгэсэн.",
      fixesLabel: "Бүртгэлээс гарсан засварууд",
      priority: { critical: "Ноцтой", high: "Өндөр", medium: "Дунд", low: "Бага" },
      fixes: [
        { problem: "Бүртгүүлэхэд давхар админ үүсдэг", priority: "high", fix: "Onboarding hook-д давтагдашгүй байдлын шалгалт", open: false },
        { problem: "Дахин сургалт 0% дээр гацдаг", priority: "high", fix: "API сургалтын бодит явцыг асуудаг болсон", open: false },
        { problem: "Нүүр хуудасны товчлуурууд ажилладаггүй", priority: "medium", fix: "Товчлуур бүрийг модуль руу нь холбосон", open: false },
        { problem: "Туршилтын гэрэл/харанхуй горимын товч", priority: "low", fix: "Тохиргоонд стандарт цэс", open: false },
        { problem: "Тохиргооны хуудсанд сесс тасардаг", priority: "critical", fix: "Сервер талын алдааг засаж байсан", open: true },
      ],
      fixed: "Засагдсан",
      open: "Тайлан бичих үед засагдаж байсан",
    },
    openCase: "Spotfixes — дэлгэрэнгүй",
  },
  path: {
    aria: "Замнал: суралцаж, ажилласан газрууд",
    eyebrow: "Туулсан зам",
    title: "Замнал",
    work: "Ажил",
    education: "Боловсрол",
    project: "Төсөл",
    /* Mongolian months are ordinal ("6-р сар", "the 6th month"); the ordinal
       suffix is the same for all twelve. */
    months: Array.from({ length: 12 }, (_, i) => `${i + 1}-р сар`),
    summer: "Зун",
    graduated: "Төгссөн",
    places: { ub: "Улаанбаатар", erie: "Эри, Пенсильвани", khanbogd: "Ханбогд" },
    placesLong: { ub: "Улаанбаатар, Монгол", erie: "Эри, Пенсильвани, АНУ" },
    transit: "Замд",
    distance: (km: number) => `≈ ${km.toLocaleString("mn-MN")} км`,
    board: "Замын бүртгэл",
    hint: "Гүйлгэх эсвэл ← → товчоор аялах",
    goTo: (title: string) => `${title} — харах`,
    gpa: "Сүүлийн 4 улирлын голч дүн",
    openCase: "Spotfixes — дэлгэрэнгүй",
    freight: "Төв оффис болон уурхайн хоорондын ачаа тээвэр",
    now: "Одоо",
  },
  caseFile: {
    label: "Төслийн дэлгэрэнгүй",
    close: "Хаах",
    overview: "Тойм",
    outcomes: "Гол үр дүн",
    stack: "Технологи",
    metrics: "Үзүүлэлт",
    links: "Холбоос",
    gallery: "Зургууд",
    role: "Үүрэг",
    year: "Он",
    category: "Төрөл",
    status: "Төлөв",
    prev: "Өмнөх",
    next: "Дараах",
    esc: "Esc — хаах",
    contents: "Агуулга",
    nextFile: "Дараагийн төсөл",
  },
  contact: {
    aria: "Холбогдох",
    title: "Холбоо барих",
    email: "И-мэйл",
    availability: "Боломж",
    based: "Байршил",
    response: "Хариу",
    responseTime: "48 цагийн дотор",
    emailMe: "И-мэйл бичих",
    copy: "Хуулах",
    copied: "Хуулсан",
    copiedLive: (email: string) => `${email} хаягийг хуулсан`,
    board: "Төлөвийн самбар",
    localTime: "Орон нутгийн цаг",
  },
  footer: {
    aria: "Хөл хэсэг",
    index: "Агуулга",
    elsewhere: "Бусад",
    top: "Дээш",
    replay: "Эхлэлийг дахин үзэх",
    credits: {
      title: "Титр",
      design: "Дизайн ба код",
      type: "Үсгийн хэв",
      built: "Ашигласан технологи",
      city: "Хотын бичлэг",
      station: "Станцын бичлэг",
      map: "Газрын зургийн өгөгдөл",
      base: "Бүтээсэн газар",
      via: "эх сурвалж",
    },
    credit:
      "GitHub болон Invertocat лого нь GitHub, Inc.-ийн барааны тэмдэг. LinkedIn болон IN лого нь LinkedIn Corporation-ийн бүртгэлтэй барааны тэмдэг.",
  },
  diagnostics: {
    title: "Оношилгоо",
    fps: "Кадрын давтамж",
    reel: "Кино",
    renderer: "Рендерер",
    quality: "Чанар",
    dpr: "Пикселийн харьцаа",
    viewport: "Дэлгэц",
    locale: "Хэл",
    motion: "Хөдөлгөөн",
    full: "Бүрэн",
    reduced: "Багасгасан",
    leds: "Интро бэх",
    none: "Байхгүй",
  },
  palette: {
    aria: "Командын цонх",
    placeholder: "Хэсэг, төсөл эсвэл үйлдэл хайх…",
    search: "Команд хайх",
    results: "Командууд",
    sections: "Хэсгүүд",
    caseFiles: "Төслүүд",
    actions: "Үйлдлүүд",
    copyEmail: "И-мэйл хаяг хуулах",
    copiedEmail: "Хуулагдлаа",
    lowPower: "Хэмнэлттэй горим",
    diagnostics: "Оношилгоо",
    replay: "Эхлэлийг дахин үзэх",
    rewrite: "Неон самбаруудыг дахин бичих",
    language: "View in English",
    on: "ИДЭВХТЭЙ",
    off: "ИДЭВХГҮЙ",
    none: (q: string) => `“${q}”-д тохирох зүйл алга.`,
    keys: "↑↓ шилжих · ↵ сонгох · esc хаах",
    count: (n: number) => `${n} илэрц`,
  },
  common: {
    newTab: "(шинэ цонхонд нээгдэнэ)",
    rewrite: "ДАХИН БИЧИХ",
  },
  notFound: {
    eyebrow: "Хуудас олдсонгүй",
    body: "Энэ хуудас байхгүй — эсвэл байсан ч одоо алга.",
    back: "Нүүр хуудас руу буцах",
  },
};

export const ui: { en: UiStrings; mn?: UiStrings } = { en, mn };
